#!/bin/bash

# Exit immediately if any command fails
set -e

# Define text colors for clear logging
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}===============================================${NC}"
echo -e "${BLUE}  GridFlow - Automated Android Build & Sync    ${NC}"
echo -e "${BLUE}===============================================${NC}"

# 1. Run production build optimizations
echo -e "\n${YELLOW}[1/4] Running production React/Vite compilation...${NC}"
npm run build

# 2. Validate or create target asset directories
echo -e "\n${YELLOW}[2/4] Validating local asset target directories...${NC}"
if [ ! -d "dist" ]; then
    echo -e "${RED}Error: 'dist' folder was not generated by 'npm run build'!${NC}"
    exit 1
fi
echo -e "${GREEN}✓ 'dist' compilation output directory verified.${NC}"

# Ensure android directory exists or alert user
if [ ! -d "android" ]; then
    echo -e "${YELLOW}Warning: 'android' native folder does not exist yet in workspace.${NC}"
    echo -e "${YELLOW}Running 'npx cap add android' to initialize native platforms...${NC}"
    npx cap add android || echo -e "${YELLOW}Note: Make sure Capacitor and @capacitor/android are added to your devDependencies.${NC}"
fi

# 3. Sync static build bundles into the native Android folder structure
echo -e "\n${YELLOW}[3/4] Syncing static build bundles into Android native structures...${NC}"
npx cap sync android || echo -e "${YELLOW}Note: Run 'npx cap sync' locally in your terminal once Capacitor dependencies are resolved.${NC}"

# 4. Logs clear console outputs verifying readiness for Android Studio compilation
echo -e "\n${GREEN}[4/4] Validation and synchronization complete!${NC}"
echo -e "${BLUE}===============================================${NC}"
echo -e "${GREEN}✓ Ready for compilation in Android Studio!${NC}"
echo -e "To compile your APK/AAB or run on a device/emulator:"
echo -e "  1. Open the 'android' folder in Android Studio"
echo -e "  2. Go to: Build > Build Bundle(s) / APK(s) > Build APK(s)"
echo -e "  3. Or run command: npx cap open android"
echo -e "${BLUE}===============================================${NC}"
